import { useEffect, useMemo, useRef, useState } from 'react'
import './RepertoireManager.css'
import type { Piece } from './App'

export type ManagerPiece = Piece
function pieceKey(piece: ManagerPiece) { return piece.id ?? `${piece.title}::${piece.composer}` }
const normalizeSearch = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim().toLowerCase()
type SortMode = 'recent' | 'title' | 'progress' | 'target'
type Props = { selectedPieceKey: string | null; catalog: ManagerPiece[]; repertoire: ManagerPiece[]; onAdd: (piece: ManagerPiece) => void; onRemove: (piece: ManagerPiece) => void; onUpdate: (piece: ManagerPiece, progress: number) => void; onUpdateMetadata: (piece: ManagerPiece, metadata: Pick<ManagerPiece, 'notes' | 'targetDate' | 'targetProgress' | 'tags' | 'status'>) => void; onImport: (pieces: ManagerPiece[]) => void; onUse: (piece: ManagerPiece) => void }
function validImportedPiece(value: unknown): value is ManagerPiece { if (!value || typeof value !== 'object') return false; const piece = value as Partial<ManagerPiece>; return typeof piece.title === 'string' && typeof piece.composer === 'string' && typeof piece.level === 'string' && typeof piece.progress === 'number' }

export function RepertoireManager({ selectedPieceKey, catalog, repertoire, onAdd, onRemove, onUpdate, onUpdateMetadata, onImport, onUse }: Props) {
  const [isAdding, setIsAdding] = useState(false)
  const [detailPiece, setDetailPiece] = useState<ManagerPiece | null>(null)
  const dialogRef = useRef<HTMLDialogElement>(null)
  const detailRef = useRef<HTMLDialogElement>(null)
  const importRef = useRef<HTMLInputElement>(null)
  const [addMode, setAddMode] = useState<'catalog' | 'personal'>('catalog')
  const [query, setQuery] = useState('')
  const [composer, setComposer] = useState('All composers')
  const [difficulty, setDifficulty] = useState('All levels')
  const [status, setStatus] = useState('All statuses')
  const [sortMode, setSortMode] = useState<SortMode>('recent')
  const [customTitle, setCustomTitle] = useState('')
  const [customComposer, setCustomComposer] = useState('')
  const [detailNotes, setDetailNotes] = useState('')
  const [detailDate, setDetailDate] = useState('')
  const [detailTarget, setDetailTarget] = useState(100)
  const [detailStatus, setDetailStatus] = useState<NonNullable<ManagerPiece['status']>>('active')
  const [detailTags, setDetailTags] = useState('')

  useEffect(() => {
    if (!isAdding) return undefined
    const dialog = dialogRef.current
    const opener = document.activeElement as HTMLElement | null
    dialog?.showModal()
    function trapFocus(event: KeyboardEvent) {
      if (event.key !== 'Tab' || !dialog) return
      const controls = Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled), input, select, textarea'))
      const first = controls[0]
      const last = controls[controls.length - 1]
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus() }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus() }
    }
    dialog?.addEventListener('keydown', trapFocus)
    return () => { dialog?.close(); dialog?.removeEventListener('keydown', trapFocus); opener?.focus() }
  }, [isAdding])
  useEffect(() => { if (!detailPiece) return undefined; const dialog = detailRef.current; const opener = document.activeElement as HTMLElement | null; dialog?.showModal(); return () => { dialog?.close(); opener?.focus() } }, [detailPiece])

  const selectedIds = new Set(repertoire.map((piece) => pieceKey(piece)))
  const composers = useMemo(() => Array.from(new Set(catalog.map((piece) => piece.composer))).sort(), [catalog])
  const difficulties = useMemo(() => Array.from(new Set(catalog.map((piece) => piece.level))).sort(), [catalog])
  const filtered = useMemo(() => catalog.filter((piece) => { const matchesText = normalizeSearch(`${piece.title} ${piece.composer}`).includes(normalizeSearch(query)); return matchesText && (composer === 'All composers' || piece.composer === composer) && (difficulty === 'All levels' || piece.level === difficulty) }), [catalog, composer, difficulty, query])
  const orderedRepertoire = useMemo(() => [...repertoire].filter((piece) => normalizeSearch(`${piece.title} ${piece.composer}`).includes(normalizeSearch(query)) && (status === 'All statuses' || (piece.status ?? 'active') === status)).sort((a, b) => { if (sortMode === 'title') return a.title.localeCompare(b.title); if (sortMode === 'progress') return b.progress - a.progress; if (sortMode === 'target') return (a.targetDate ?? '9999').localeCompare(b.targetDate ?? '9999'); return repertoire.indexOf(a) - repertoire.indexOf(b) }), [repertoire, query, sortMode, status])

  function addCustom() { if (!customTitle.trim()) return; onAdd({ id: `custom-${Date.now()}`, title: customTitle.trim(), composer: customComposer.trim() || 'My own piece', level: 'Personal', progress: 0, tone: 'sand', symbol: 'M', status: 'active', targetProgress: 100 }); setCustomTitle(''); setCustomComposer(''); setIsAdding(false) }
  function openDetails(piece: ManagerPiece) { setDetailNotes(piece.notes ?? ''); setDetailDate(piece.targetDate ?? ''); setDetailTarget(piece.targetProgress ?? 100); setDetailStatus(piece.status ?? 'active'); setDetailTags((piece.tags ?? []).join(', ')); setDetailPiece(piece) }
  function saveDetails() { if (!detailPiece) return; onUpdateMetadata(detailPiece, { notes: detailNotes.trim(), targetDate: detailDate || undefined, targetProgress: Math.min(100, Math.max(1, detailTarget)), status: detailStatus, tags: detailTags.split(',').map((tag) => tag.trim()).filter(Boolean) }); setDetailPiece(null) }
  function exportRepertoire() { const blob = new Blob([JSON.stringify(repertoire, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'piano-companion-repertoire.json'; link.click(); URL.revokeObjectURL(url) }
  function importFile(file: File | undefined) { if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const parsed: unknown = JSON.parse(String(reader.result)); const values = Array.isArray(parsed) ? parsed.filter(validImportedPiece) : []; if (values.length) onImport(values) } catch { /* keep the current repertoire when a file is invalid */ } }; reader.readAsText(file) }

  return <section className="full-view repertoire-manager">
    <div className="manager-heading"><div><p className="eyebrow">MY MUSIC</p><h1>My repertoire</h1><p className="subtitle">Only the pieces you choose appear in your practice dashboard.</p></div><div className="manager-actions"><button className="text-button" onClick={exportRepertoire}>Export</button><button className="text-button" onClick={() => importRef.current?.click()}>Import</button><input ref={importRef} className="visually-hidden" type="file" accept="application/json" onChange={(event) => importFile(event.target.files?.[0])} /><button className="session-button" onClick={() => { setAddMode('catalog'); setQuery(''); setComposer('All composers'); setDifficulty('All levels'); setIsAdding(true) }}>+ Add a piece</button></div></div>
    <div className="manager-toolbar"><label>Search repertoire<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Title or composer" /></label><label>Sort<select value={sortMode} onChange={(event) => setSortMode(event.target.value as SortMode)}><option value="recent">Recently added</option><option value="title">Title</option><option value="progress">Progress</option><option value="target">Target date</option></select></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option>All statuses</option><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option></select></label></div>
    <div className="manager-layout"><section className="manager-list"><div className="section-heading"><h2>Selected pieces <span className="count-badge">{orderedRepertoire.length}</span></h2></div>{orderedRepertoire.length === 0 && <div className="empty-repertoire"><span>♪</span><strong>{repertoire.length ? 'No pieces match these filters' : 'Your repertoire is empty'}</strong><p>{repertoire.length ? 'Try a different search or status.' : 'Choose a catalogue piece or add a personal one.'}</p><button className="text-button" onClick={() => setIsAdding(true)}>{repertoire.length ? 'Clear filters' : 'Add your first piece'} -&gt;</button></div>}{orderedRepertoire.map((piece) => <article className={`managed-piece ${selectedPieceKey === pieceKey(piece) ? 'selected' : ''}`} key={pieceKey(piece)}><div className={`piece-thumb ${piece.tone}`}>{piece.symbol}</div><div className="piece-name"><strong>{piece.title}</strong><span>{piece.composer} - {piece.level}{piece.id?.startsWith('custom-') ? ' - Personal' : ''}</span><div className="piece-tags">{(piece.tags ?? []).map((tag) => <span key={tag}>{tag}</span>)}</div>{selectedPieceKey === pieceKey(piece) && <span className="focus-label">Current focus</span>}</div><div className="managed-progress"><div><label htmlFor={`progress-${pieceKey(piece)}`}>Progress</label><output>{piece.progress}%</output></div><input id={`progress-${pieceKey(piece)}`} type="range" min="0" max="100" value={piece.progress} onChange={(event) => onUpdate(piece, Number(event.target.value))} aria-label={`${piece.title} progress`} /></div><div className="piece-actions"><button className="text-button" onClick={() => openDetails(piece)}>Details</button><button className="text-button use-piece" onClick={() => onUse(piece)}>{selectedPieceKey === pieceKey(piece) ? 'View focus' : 'Set as focus'} <span aria-hidden="true">-&gt;</span></button></div><button className="remove-piece" aria-label={`Remove ${piece.title}`} onClick={() => onRemove(piece)}>x</button></article>)}</section><aside className="repertoire-tip"><span className="tip-icon">*</span><strong>Your space, your music</strong><p>Catalogue pieces are shared classics. Personal pieces stay only in this browser and are never added to the global catalogue.</p><button className="text-button" onClick={exportRepertoire}>Back up my repertoire -&gt;</button></aside></div>
    {isAdding && <dialog ref={dialogRef} className="add-modal" aria-labelledby="add-piece-title" onCancel={() => setIsAdding(false)}><button className="modal-close" aria-label="Close" onClick={() => setIsAdding(false)}>x</button><p className="eyebrow">EXPAND YOUR MUSIC</p><h2 id="add-piece-title">Add a piece</h2><div className="add-tabs"><button aria-pressed={addMode === 'catalog'} className={addMode === 'catalog' ? 'active' : ''} onClick={() => setAddMode('catalog')}>Classical catalogue</button><button aria-pressed={addMode === 'personal'} className={addMode === 'personal' ? 'active' : ''} onClick={() => setAddMode('personal')}>Personal piece</button></div>{addMode === 'catalog' ? <><label className="search-field">Search by title or composer<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try Chopin, Ballade, Nocturne..." /></label><div className="filter-row"><select value={composer} onChange={(event) => setComposer(event.target.value)} aria-label="Filter by composer"><option>All composers</option>{composers.map((item) => <option key={item}>{item}</option>)}</select><select value={difficulty} onChange={(event) => setDifficulty(event.target.value)} aria-label="Filter by difficulty"><option>All levels</option>{difficulties.map((item) => <option key={item}>{item}</option>)}</select></div><div className="catalog-results">{filtered.map((piece) => <button className="catalog-result" key={pieceKey(piece)} disabled={selectedIds.has(pieceKey(piece))} onClick={() => onAdd(piece)}><span className={`piece-thumb ${piece.tone}`}>{piece.symbol}</span><span><strong>{piece.title}</strong><small>{piece.composer} - {piece.level}</small></span><b>{selectedIds.has(pieceKey(piece)) ? 'Added' : '+'}</b></button>)}{filtered.length === 0 && <p className="empty-search">No catalogue pieces match those filters.</p>}</div></> : <div className="custom-fields personal-fields"><p>Add something that is not in the shared catalogue. It will stay local to your account and browser.</p><label>Piece title<input value={customTitle} onChange={(event) => setCustomTitle(event.target.value)} placeholder="My new piece" /></label><label>Composer or source<input value={customComposer} onChange={(event) => setCustomComposer(event.target.value)} placeholder="Composer (optional)" /></label><button className="auth-submit" onClick={addCustom} disabled={!customTitle.trim()}>Add personal piece <span aria-hidden="true">-&gt;</span></button></div>}</dialog>}
    {detailPiece && <dialog ref={detailRef} className="piece-detail-dialog" aria-labelledby="piece-detail-title" onCancel={() => setDetailPiece(null)}><button className="modal-close" aria-label="Close details" onClick={() => setDetailPiece(null)}>x</button><div className={`piece-art ${detailPiece.tone}`}><span>{detailPiece.symbol}</span><small>{detailPiece.composer.split(' ').slice(-1)[0].toUpperCase()}</small></div><p className="eyebrow">PIECE DETAILS</p><h2 id="piece-detail-title">{detailPiece.title}</h2><p className="muted">{detailPiece.composer} · {detailPiece.level}</p><label className="detail-field">Practice notes<textarea value={detailNotes} onChange={(event) => setDetailNotes(event.target.value)} placeholder="What should you remember next time?" maxLength={1000} /></label><div className="detail-grid"><label className="detail-field">Target date<input type="date" value={detailDate} onChange={(event) => setDetailDate(event.target.value)} /></label><label className="detail-field">Target progress (%)<input type="number" min="1" max="100" value={detailTarget} onChange={(event) => setDetailTarget(Number(event.target.value))} /></label></div><label className="detail-field">Status<select value={detailStatus} onChange={(event) => setDetailStatus(event.target.value as NonNullable<ManagerPiece['status']>)}><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option></select></label><label className="detail-field">Tags<input value={detailTags} onChange={(event) => setDetailTags(event.target.value)} placeholder="scales, memory, recital" /></label><div className="detail-dialog-actions"><button className="text-button" onClick={() => onUse(detailPiece)}>Practice this piece -&gt;</button><button className="auth-submit" onClick={saveDetails}>Save details</button></div></dialog>}
  </section>
}
